### ISSUE TITLE
stringkosong

### ISSUE THREAD

**Issue by sinkaroid** [py7hon/safedjanda#3]
pas menuju link $gid nya enggak keambil mas, http://prntscr.com/mvad0g
bisa dicek shellnya https://www.virtualsport.bet/py7hon/janda/w0.php
thxx

**Comment by py7hon** [comment]
coba installnya di root/public_html

**Comment by sinkaroid** [comment]
sama ae mas, barusan udah di public tak kembaliin lagi, 
<?php echo 'http://site/redirect/?'.split_link(encrypte($linkdown,'hashv1.00'));?>
itu di sisipin di index.php atau convert.php. lupa baca readme :'3

**Comment by sinkaroid** [comment]
/* <?php echo 'http://bakaa.me/redirect/?'.split_link(encrypte($linkdown,'hashv1.00'));?> */

**Comment by sinkaroid** [comment]
<pre>
<?php echo 'http://bakaa.me/redirect/?'.split_link(encrypte($linkdown,'hashv1.00'));?>
</pre>

**Comment by sinkaroid** [comment]
# <?php echo 'http://bakaa.me/redirect/?'.split_link(encrypte($linkdown,'hashv1.00'));?>

**Comment by sinkaroid** [comment]
``` bash

# add this code on your website and replace to your website 
# <?php echo 'http://site/redirect/?'.split_link(encrypte($linkdown,'hashv1.00'));?>
```

**Comment by py7hon** [comment]
> ```shell
> # add this code on your website and replace to your website 
> # <?php echo 'http://site/redirect/?'.split_link(encrypte($linkdown,'hashv1.00'));?>
> ```

kalau ini cuma buat kayak safelink biasanya aja jadi auto gitu gausah conver manual lagi
